name: Publish-PDF

on: push

jobs:
  publish-pdfs:
    name: Publish PDFs for the stories
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'build')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List Stories
        run: |
          mkdir output
          echo "INFILES=$(find wiki/stories/ -name '*.md' -type f | sort | xargs printf '"%s" ')" >> $GITHUB_ENV

      - name: Generate PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --toc
            --output=output/Stories_from_Decorat.pdf scripts/header.md ${{ env.INFILES }}
      
      - name: Word Counts
        run: |
          chmod +x scripts/word_counts.sh
          ./scripts/word_counts.sh wiki/stories/ > output/word_counts.csv

      - name: Publish artifact - PDF
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output/Stories_from_Decorat.pdf

      - name: Publish artifact - Word Counts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output/word_counts.csv

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: running #${{ github.ref }}
          release_name: Running Release #${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset - PDF
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/Stories_from_Decorat.pdf
          asset_name: Stories_from_Decorat.pdf
          asset_content_type: application/pdf

      - name: Upload Release Asset - Word Counts
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/word_counts.csv
          asset_name: word_counts.csv
          asset_content_type: text/csv

